### ISSUE TITLE
Does this work on Debian 11?

### ISSUE THREAD

**Issue by gmiranda** [DazzyWalkman/lxd-openwrt-simplified#2]
I'm having issues with Debian 11, which defaults to nftables on a Raspberry 4 (DietPi) with the linuxcontainers image and was wondering if your building script could be helpful.

The issue seems to be that as soon as I start the docker service after the OpenWRT LXC container is running, it "breaks" the LXC network: I can't reliable ssh or http into the container from a computer other than the host. It will not also route any traffic (other than the host's). I've sort of traced this issue to docker doing something with iptables but I've not gotten any further.

Calling update-alternatives to default to iptables-legacy did not change a thing.

**Comment by DazzyWalkman** [comment]
It may work on Debian 11. I use this script along with my oplxc4pve script on PVE 7.0, which is based on Debian 11, may with network slightly altered.

As in your case, it seems you are trying to make lxc network and docker network co-exist.  Unfortunately, I have little knowledge about this.

Maybe you'd like to switch solely to docker, and running OpenWrt as docker container, which is supported by OpenWrt officially, while lxc is not.

There are constantly updated toolsets published at dockerhub: https://hub.docker.com/u/openwrtorg
And also codes and documentation: https://github.com/openwrt/docker
Hope it help.

**Comment by gmiranda** [comment]
Thank you very much for your reply! As far as I can remember OpenWRT was not possible in my scenario, but I will look again into it.

Right now (OpenWRT LXC) the  problem is not docker per se, it's iptables. With docker out of the picture, if I fire up wireguard (which will setup a few iptables rules), I get the same result. It only works if I clean the host's iptables rules, set update-alternatives to iptables-legacy and then fire up wireguard. It seems that it's possible to have both nftables and iptables-legacy but it sure looks complicated!
